runtime: python311
entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT


env_variables:
  DB_CONNECTION_NAME: "my-project-suspension:us-central1:user-cloud-db"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "Nube1234@"


handlers:
  - url: /.*
    script: auto