runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app


env_variables:
  DB_CONNECTION_NAME: 'my-project-suspension:us-central1:user-cloud-db'
  DB_NAME: 'postgres'
  DB_USER: 'postgres'
  DB_PASSWORD: 'Nube1234@'